sudo: false
language: rust

env:
  global:
    - CRATE=confluence

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: nightly
      env: DOC=true
    - rust: beta
    - rust: stable
    - rust: 1.3.0

after_success:
  - /bin/bash export_doc.sh
